#!/usr/bin/env bash

interface_state() {
    echo $1 | rg "$2.*: .* state UP" | rg -o "$2"
}

wl=$(interface_state "$(ip link)" wlp)
eth=$(interface_state "$(ip link)" enp) # TODO: is this the right interface name

echo $wl $eth

ip monitor link | while read -r line; do
    wl_part=$(echo $line | rg "wlp.*: .* state (DOWN|UP)")
    [ ! -z "$wl_part" ] && wl=$(interface_state "$line" wlp)

    eth_part=$(echo $line | rg "enp.*: .* state (DOWN|UP)")
    [ ! -z "$eth_part" ] && eth=$(interface_state "$line" enp)

    echo $wl $eth
done
